version: "3"
services:
    app:
      container_name: webapi
      restart: always
      build: 
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - mongo
    mongo:
      container_name: mongo
      image: mongo
      restart: always 